/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Control_CuentasEmpresa;

import Control_Empleados.*;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ernes
 */
public class jd_AgregarSaldo extends javax.swing.JDialog {
    private int FilaSeleccionada;
    private DefaultTableModel modelo;    
    String NombreBanco, NumeroCuenta, Saldo;
    /**
     * Creates new form jd_AgregarEmpleado
     */
    public jd_AgregarSaldo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        modelo =(DefaultTableModel) tblSaldos.getModel();
        MostrarSaldos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBanco = new javax.swing.JTextField();
        txtCuenta = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelarE = new javax.swing.JButton();
        btnLimpiarE = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jspAgregarSaldo = new javax.swing.JSpinner();
        cbxCuenta = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSaldos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Banco:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Número de Cuenta:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Monto:");

        txtBanco.setEditable(false);
        txtBanco.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBancoActionPerformed(evt);
            }
        });

        txtCuenta.setEditable(false);
        txtCuenta.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N

        btnGuardar.setBackground(new java.awt.Color(204, 255, 204));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editar.png"))); // NOI18N
        btnGuardar.setText("Modificar");
        btnGuardar.setActionCommand("Agregar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelarE.setBackground(new java.awt.Color(255, 204, 204));
        btnCancelarE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelarE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancelar.png"))); // NOI18N
        btnCancelarE.setText("Cancelar");
        btnCancelarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEActionPerformed(evt);
            }
        });

        btnLimpiarE.setBackground(new java.awt.Color(255, 255, 204));
        btnLimpiarE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLimpiarE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/limpiar.png"))); // NOI18N
        btnLimpiarE.setText("Limpiar");
        btnLimpiarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarEActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Modificar Saldo de Cuentas");

        jspAgregarSaldo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jspAgregarSaldo.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 0.25f));

        cbxCuenta.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbxCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sumar", "Restar" }));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Evento:");

        tblSaldos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblSaldos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Banco", "Cuenta", "Saldo total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSaldos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSaldosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSaldos);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inflacion.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jspAgregarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(191, 191, 191))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbxCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jspAgregarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiarE)
                    .addComponent(btnCancelarE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        ModificaSaldo();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarEActionPerformed
        // TODO add your handling code here:
        limpiar();
        MostrarSaldos();        
    }//GEN-LAST:event_btnLimpiarEActionPerformed

    private void btnCancelarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarEActionPerformed

    private void txtBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBancoActionPerformed

    private void tblSaldosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSaldosMouseClicked
        // TODO add your handling code here:
        FilaSeleccionada = tblSaldos.rowAtPoint(evt.getPoint());
        CapturarCuenta();
    }//GEN-LAST:event_tblSaldosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jd_AgregarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jd_AgregarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jd_AgregarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jd_AgregarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            jd_AgregarSaldo dialog = new jd_AgregarSaldo(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }
    
    public void ModificaSaldo(){
        try {
        String NombreBanco, NumeroCuenta, Evento;
        Double Monto; double Credito = 0; double Debito = 0;
               
        if (Double.parseDouble(jspAgregarSaldo.getValue().toString()) < 0 ) {
            JOptionPane.showMessageDialog(this, "ingrese un monto mayor a cero", "Notificación" , JOptionPane.INFORMATION_MESSAGE);
            jspAgregarSaldo.setValue(0);
            return;
        }        
                        
        NombreBanco = txtBanco.getText().toString();
        NumeroCuenta= txtCuenta.getText().toString();
        Evento = cbxCuenta.getSelectedItem().toString();
        Monto = Double.parseDouble(jspAgregarSaldo.getValue().toString());
                     
        if (Evento.equals("Sumar")) {
            Credito = Monto;
        }else{
            
            double SaldoActual = Double.parseDouble(SumarSaldo(NumeroCuenta));
            
             if ((SaldoActual - Monto) < 0) {
                JOptionPane.showMessageDialog(this, "Monto ingresado no permitido debido a que el saldo queda negativo", "Error" , JOptionPane.ERROR_MESSAGE);
                return;
             }            
            Debito = Monto;
        }                       
             
        if (JOptionPane.showConfirmDialog(this, "Desea agregar el nuevo movimiento?", "WARNING", JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION) {
          return;
        }
        
        MovimientosCuentas movimientos = new MovimientosCuentas(NumeroCuenta, String.valueOf(Credito), String.valueOf(Debito));
        
        MovimientosCuentasDAO movimientosCuentasDAO = new MovimientosCuentasDAO();
        movimientosCuentasDAO.CrearMovimientoCuentas(movimientos);
                      
        JOptionPane.showMessageDialog(this, "Movimiento generado exitosamente", "Notificación" , JOptionPane.INFORMATION_MESSAGE);
        
        limpiar();
        MostrarSaldos();
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error al actualizar el Empleado", "Error" , JOptionPane.ERROR_MESSAGE);
            return;
        }
    }
    
      public void MostrarSaldos(){
        try {                  
            List<Cuentas> listaCuentas = new ArrayList<>();   
            CuentasDAO cuentasDAO = new CuentasDAO(); 
            listaCuentas = cuentasDAO.leerCuentas(); 
                      
            
            //Limpieza de la tabla
            int filas = modelo.getRowCount();
            for (int a = 0; filas > a; a++) {
                modelo.removeRow(0);
            }    
            
            for (Cuentas cuenta : listaCuentas) {               
                
                NombreBanco = cuenta.getNombreBanco().toString();
                NumeroCuenta = cuenta.getCuenta().toString();        
                
                String Saldo = SumarSaldo(NumeroCuenta);
                
                modelo.addRow(new Object[]{NombreBanco, NumeroCuenta, Saldo});
            }
                                    
                   
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error al cargar usuarios", "Error" , JOptionPane.ERROR_MESSAGE);
            return;
        }
    }
      
     public String SumarSaldo(String NumeroCuenta){
         
         try {
             
            List<MovimientosCuentas> listaMovimientos = new ArrayList<>();   
            MovimientosCuentasDAO movimientosCuentasDAO = new MovimientosCuentasDAO(); 
            listaMovimientos = movimientosCuentasDAO.leerMovimientosCuentas(); 
            
            double Creditos = 0.0; double Debitos = 0.0; double Sumatoria = 0.0;
            String Saldo;
            
            for (MovimientosCuentas movimientos : listaMovimientos) {               
                if (movimientos.getNumeroCuenta().equals(NumeroCuenta)) {
                    Creditos += Double.parseDouble(movimientos.getCreditos());
                    Debitos += Double.parseDouble(movimientos.getDebitos());
                }
            }
            
            Sumatoria = Creditos - Debitos;               
            Saldo = String.valueOf(Sumatoria);
                      
            return Saldo;
             
         } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Ha ocurrido un error al calcular el saldo", "Error" , JOptionPane.ERROR_MESSAGE);
            return "";
         }
     }
   
    
    public void limpiar(){
        
        txtBanco.setText("");
        txtCuenta.setText("");
        jspAgregarSaldo.setValue(0);
        cbxCuenta.setSelectedIndex(0);
        
    }
  public boolean ValidarEmpleado(String IdEmpleado, String IdEmpleadoNuevo){
        
        try {
            boolean existe = false;
            List<Empleado> empleadoList = new ArrayList<>();            
            EmpleadoDAO empleadoDAO = new EmpleadoDAO(); //Llama al dao de usuario
            empleadoList = empleadoDAO.leerEmpleado();
            
            empleadoList.remove(IdEmpleado);
            
            for (Empleado us : empleadoList) {
            
                 if (us.getIdEmpleado().equals(IdEmpleadoNuevo)) {
                    existe = true;
                    break;
                }
            }
            
            return existe;
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error al guardar el empleado", "Error" , JOptionPane.ERROR_MESSAGE);
            return false;
        }
    
    }
  
  public class DetalleCuentasDTO {
    private String NombreBanco;
    private String Cuenta;
    private String Saldo; 
}
  
  private void CapturarCuenta(){      
      try {                  
        //Obtenemmos los datos de la fila seleccionada  
        txtBanco.setText(String.valueOf(tblSaldos.getValueAt(FilaSeleccionada, 0)));
        txtCuenta.setText(String.valueOf(tblSaldos.getValueAt(FilaSeleccionada, 1)));
                        
      } catch (Exception e) {
          System.out.println("Error cargando datos");
      }
   
      
  }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarE;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiarE;
    private javax.swing.JComboBox<String> cbxCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jspAgregarSaldo;
    private javax.swing.JTable tblSaldos;
    private javax.swing.JTextField txtBanco;
    private javax.swing.JTextField txtCuenta;
    // End of variables declaration//GEN-END:variables

  
}
