/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Control_Usuario;

import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * 
 */
public class jd_ModificarUsuario extends javax.swing.JDialog {

    /**
     * Creates new form jd_AgregarUsuario
     */
    public jd_ModificarUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        txtcontrasena2 = new javax.swing.JPasswordField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Usuario");
        setBackground(new java.awt.Color(102, 102, 255));
        setName("jd_ModificarUsuario"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Modificación de usuario");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Usuario");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Repetir Contraseña");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Contraseña");

        txtUsuario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtContrasena.setBackground(new java.awt.Color(204, 204, 204));
        txtContrasena.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtContrasena.setEnabled(false);

        txtcontrasena2.setBackground(new java.awt.Color(204, 204, 204));
        txtcontrasena2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtcontrasena2.setEnabled(false);

        btnAceptar.setBackground(new java.awt.Color(204, 255, 204));
        btnAceptar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 204, 204));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intimidad.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(txtUsuario)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAceptar)
                                .addGap(131, 131, 131)
                                .addComponent(btnCancelar))
                            .addComponent(txtcontrasena2))))
                .addGap(13, 13, 13)
                .addComponent(btnBuscar)
                .addGap(99, 99, 99))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnBuscar))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtcontrasena2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        ModificarContrasena();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
       this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        ValidarUsuario();
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jd_ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jd_ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jd_ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jd_ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jd_ModificarUsuario dialog = new jd_ModificarUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
// Método para validar la existencia de un usuario antes de modificar la contraseña
public void ValidarUsuario() {
    try {
        String _usuario; // Variable para almacenar el nombre de usuario a validar

        // Validar que se haya ingresado un nombre de usuario
        if (txtUsuario.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese el Usuario", "Notificación", JOptionPane.INFORMATION_MESSAGE);
            return; // Salir del método si no se ha ingresado un nombre de usuario
        }

        _usuario = txtUsuario.getText().toString(); // Obtener el nombre de usuario desde el campo de texto

        // Crear una lista para almacenar los usuarios leídos desde la base de datos
        List<Usuario> usuarios = new ArrayList<>();

        // Crear una instancia de UsuariosDAO para acceder a los métodos de lectura de usuarios
        UsuariosDAO usuariosDAO = new UsuariosDAO();

        // Leer todos los usuarios desde la base de datos y almacenarlos en la lista usuarios
        usuarios = usuariosDAO.leerUsuarios();

        boolean existe = false; // Variable para indicar si el usuario existe en la base de datos

        // Verificar si el nombre de usuario existe en la lista de usuarios
        for (Usuario us : usuarios) {
            if (us.getNombreUsuario().equals(_usuario)) {
                existe = true; // Cambiar existe a true si se encuentra el nombre de usuario en la base de datos
                break; // Salir del bucle porque ya se encontró el nombre de usuario
            }
        }

        // Si el usuario no existe, mostrar un mensaje de error y salir del método
        if (!existe) {
            JOptionPane.showMessageDialog(this, "El Usuario ingresado no existe", "Notificación", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Habilitar campos para modificar contraseña y cambiar el color de fondo
        txtUsuario.setEnabled(false);
        txtContrasena.setEnabled(true);
        txtcontrasena2.setEnabled(true);
        txtContrasena.setBackground(Color.GREEN);
        txtcontrasena2.setBackground(Color.GREEN);

    } catch (Exception e) {
        // Capturar y mostrar cualquier error que ocurra durante la validación del usuario
        JOptionPane.showMessageDialog(this, "Ha ocurrido un error al buscar el usuario", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Salir del método en caso de error
    }
}
    // Método para modificar la contraseña de un usuario validado
public void ModificarContrasena() {
    try {
        String _usuario, _contrasena, _contrasena2;

        // Validar que se haya ingresado la nueva contraseña
        if (txtContrasena.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese la Contraseña", "Notificación", JOptionPane.INFORMATION_MESSAGE);
            return; // Salir del método si no se ha ingresado la contraseña
        }

        // Validar que se haya ingresado la confirmación de la contraseña
        if (txtcontrasena2.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese la contraseña de confirmación", "Notificación", JOptionPane.INFORMATION_MESSAGE);
            return; // Salir del método si no se ha ingresado la confirmación de la contraseña
        }

        _usuario = txtUsuario.getText().toString(); // Obtener el nombre de usuario desde el campo de texto
        _contrasena = txtContrasena.getText().toString(); // Obtener la nueva contraseña desde el campo de texto
        _contrasena2 = txtcontrasena2.getText().toString(); // Obtener la confirmación de la contraseña desde el campo de texto

        // Validar que las contraseñas coincidan
        if (!_contrasena.equals(_contrasena2)) {
            JOptionPane.showMessageDialog(this, "Las Contraseñas no coinciden", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Salir del método si las contraseñas no coinciden
        }

        // Confirmar si el usuario desea actualizar la contraseña
        if (JOptionPane.showConfirmDialog(this, "Desea actualizar el usuario?", "WARNING", JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION) {
            return; // Salir del método si el usuario cancela la actualización
        }

        // Crear un objeto Usuario con el usuario y la nueva contraseña
        Usuario usuario = new Usuario(_usuario, _contrasena);

        // Crear una instancia de UsuariosDAO para acceder a los métodos de actualización de usuario
        UsuariosDAO usuariosDAO = new UsuariosDAO();

        // Llamar al método actualizarUsuario de UsuariosDAO para actualizar la contraseña del usuario
        usuariosDAO.actualizarUsuario(_usuario, usuario);

        // Limpiar los campos de texto y restablecer colores de fondo después de actualizar exitosamente
        txtUsuario.setText("");
        txtContrasena.setText("");
        txtcontrasena2.setText("");
        txtContrasena.setBackground(Color.RED);
        txtcontrasena2.setBackground(Color.RED);
        txtUsuario.setEnabled(true);
        txtContrasena.setEnabled(false);
        txtcontrasena2.setEnabled(false);

        // Mostrar un mensaje de éxito al usuario
        JOptionPane.showMessageDialog(this, "Usuario guardado exitosamente", "Notificación", JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception e) {
        // Capturar y mostrar cualquier error que ocurra durante la modificación de la contraseña
        JOptionPane.showMessageDialog(this, "Ha ocurrido un error al guardar el usuario", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Salir del método en caso de error
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JPasswordField txtcontrasena2;
    // End of variables declaration//GEN-END:variables
}
