/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pago__Nomina;

import Control_Empleados.Empleado;
import Control_Empleados.EmpleadoDAO;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author 
 */
public class jd_Nomina extends javax.swing.JDialog {
    EmpleadoDAO empleadoDAO = new EmpleadoDAO(); //Llama al dao de usuario
    List<Empleado> empleadoList = new ArrayList<>();     
    private DefaultTableModel modelo;

    /**
     * Creates new form jd_Nomina
     */
    public jd_Nomina(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null); //Para poner centrado el jdialog        
        modelo =(DefaultTableModel) tblNomina.getModel();
        CalculosNomina();

    }

    jd_Nomina() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCancelarE = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNomina = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nomina Individual");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(204, 204, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N

        btnCancelarE.setBackground(new java.awt.Color(255, 204, 204));
        btnCancelarE.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnCancelarE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cerrar-sesion.png"))); // NOI18N
        btnCancelarE.setText("salir");
        btnCancelarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEActionPerformed(evt);
            }
        });

        tblNomina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblNomina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Completo", "Cargo", "Salario mensual", "Inss Laboral", "Salario - INSS", "IR", "Salario a Recibido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblNomina);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salario (1).png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel6.setText("\"Nómina General\"       ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancelarE, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(194, 194, 194)
                            .addComponent(jLabel1)
                            .addGap(181, 181, 181)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(371, 371, 371))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnCancelarE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarEActionPerformed

    public void CalculosNomina(){     
        
        try {
              
            List<Empleado> empleado = new ArrayList<>(); 
            EmpleadoDAO empleadoDAO = new EmpleadoDAO(); //Llama al dao de usuario
            empleado = empleadoDAO.leerEmpleado(); 

            for (Empleado emp : empleado) {   

                Double SalarioBruto, DeduccionInss, SalarioMenosInss, IR, SalarioNeto;
                String NombreCompleto, Cargo;
                DecimalFormat decimalFormat = new DecimalFormat("#.##");

                NombreCompleto = emp.getNombreEmpleado().toString() + " " + emp.getApellidoEmpleado().toString();   
                Cargo = emp.getPuestoEmpleado();
                SalarioBruto = Double.parseDouble(emp.getSalario_Fijo().toString());             

                DeduccionInss = Double.parseDouble(decimalFormat.format((SalarioBruto * 0.07)));
                SalarioMenosInss = SalarioBruto - DeduccionInss;

                //Calculo del IR
                Double Salariox12, SobreExceso, MenosSobreExceso, ImpuestoBase; Double PorcentajeAplicable = 0.00;

                Salariox12 = SalarioMenosInss * 12; 
                double[] arreglo = CalcularSobreExceso(Salariox12);        
                SobreExceso = arreglo[0]; 
                MenosSobreExceso = Salariox12 - SobreExceso; 
                if (arreglo[1] > 0) {
                    PorcentajeAplicable = MenosSobreExceso * (arreglo[1] / 100);
                }        
                ImpuestoBase = PorcentajeAplicable + arreglo[2];        
                IR = Double.parseDouble(decimalFormat.format((ImpuestoBase / 12)));        
                //Fin calculo de IR

                SalarioNeto = SalarioMenosInss - IR;

                modelo.addRow(new Object[]{NombreCompleto, Cargo, SalarioBruto, DeduccionInss, SalarioMenosInss, IR, SalarioNeto});
            } 
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Ha ocurrido un error al cargar la lista de Empleados", "Error" , JOptionPane.ERROR_MESSAGE);
            return;
        }
    }
    
    public double[] CalcularSobreExceso(double Salariox12){
        double[] arreglo = new double[3];
        int valor = 0; int PorcentajeAplicable = 0; int ImpuestoBase = 0;
        
        if (Salariox12 > 0.01 && Salariox12 <= 100000) {
            valor  = 0;
            PorcentajeAplicable = 0;
            ImpuestoBase = 0;
        }else if (Salariox12 > 100000.01 && Salariox12 <= 200000) {
            valor  = 100000;
            PorcentajeAplicable = 15;
            ImpuestoBase = 0;
        }else if (Salariox12 > 200000.01 && Salariox12 <= 350000) {
            valor  = 200000;
            PorcentajeAplicable = 20;
            ImpuestoBase = 15000;
        }else if (Salariox12 > 350000.01 && Salariox12 <= 500000) {
            valor  = 350000;
            PorcentajeAplicable = 25;
            ImpuestoBase = 45000;
        }else if (Salariox12 > 500000.01) {
            valor  = 500000;
            PorcentajeAplicable = 30;
            ImpuestoBase = 82500;
        }
    
        arreglo[0] = valor;
        arreglo[1] = PorcentajeAplicable;
        arreglo[2] = ImpuestoBase;
        
        return arreglo;
    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jd_Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jd_Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jd_Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jd_Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jd_Nomina dialog = new jd_Nomina(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNomina;
    // End of variables declaration//GEN-END:variables
}
