/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pago__Nomina;

import Control_Empleados.Empleado;
import Control_Empleados.EmpleadoDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author 
 */
public class jd_Nomina extends javax.swing.JDialog {
    EmpleadoDAO empleadoDAO = new EmpleadoDAO(); //Llama al dao de usuario
    List<Empleado> empleadoList = new ArrayList<>();     
    private DefaultTableModel modelo;

    /**
     * Creates new form jd_Nomina
     */
    public jd_Nomina(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null); //Para poner centrado el jdialog        
        //modelo =(DefaultTableModel) tblEmpleados.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtidEmpleado = new javax.swing.JTextField();
        btnGenerarNomina = new javax.swing.JButton();
        btnCancelarE = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nomina Individual");

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Id del Empleado:");

        txtidEmpleado.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtidEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidEmpleadoActionPerformed(evt);
            }
        });

        btnGenerarNomina.setBackground(new java.awt.Color(0, 204, 153));
        btnGenerarNomina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGenerarNomina.setForeground(new java.awt.Color(0, 0, 0));
        btnGenerarNomina.setText("Generar");
        btnGenerarNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarNominaActionPerformed(evt);
            }
        });

        btnCancelarE.setBackground(new java.awt.Color(255, 0, 51));
        btnCancelarE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelarE.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelarE.setText("Cancelar");
        btnCancelarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Completo", "Cargo", "Salario mensual", "Inss Laboral", "Salario - INSS", "IR", "Salario a Recibir"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGenerarNomina, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtidEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerarNomina)
                    .addComponent(btnCancelarE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidEmpleadoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtidEmpleadoActionPerformed

    private void btnGenerarNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarNominaActionPerformed
        // TODO add your handling code here:
        
        if (txtidEmpleado.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese el Id de Empleado", "Notificación" , JOptionPane.INFORMATION_MESSAGE);
            return;
        }     
        if (!ValidarEmpleado(txtidEmpleado.getText())) {
            JOptionPane.showMessageDialog(this, "El Empleado ingresado no Existe", "Notificación" , JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        Nomina(txtidEmpleado.getText());           
        
    }//GEN-LAST:event_btnGenerarNominaActionPerformed

    private void btnCancelarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarEActionPerformed

    public void Nomina(String IdEmpleado){
        String NombreComleto, Cargo, PuestoEmpleado, IR;
        double Salario_Fijo, SalarioMensual, insssLaboral;
        try {
            boolean existe = false;
            List<Empleado> empleadoList = new ArrayList<>(); 
            empleadoList = empleadoDAO.leerEmpleado();   
            
             for (Empleado emp : empleadoList) {            
                 if (emp.getIdEmpleado().equals(IdEmpleado)) {  
                    NombreComleto = (emp.getNombreEmpleado() + " " + emp.getApellidoEmpleado());
                    Cargo = emp.getPuestoEmpleado();
                    SalarioMensual = emp.getSalario_Fijo();
                    //nsssLaboral = (SalarioMensual) * 0.07);
                    
                    // modelo.addRow(new Object[]{IdEmpleado, NombreComleto, PuestoEmpleado, Salario_Fijo});
                    
                    existe = true;
                    break;
                }
            }
            
            if (!existe) {
                JOptionPane.showMessageDialog(this, "El Empleado ingresado no existe", "Notificación" , JOptionPane.INFORMATION_MESSAGE);
                return;
            }            
            
          
        
            
        } catch (Exception e) {
        }
        
    }
    
     public boolean ValidarEmpleado(String IdEmpleado){
        
        try {
            boolean existe = false;
            empleadoList = empleadoDAO.leerEmpleado();           
                       
            for (Empleado us : empleadoList) {            
                 if (us.getIdEmpleado().equals(IdEmpleado)) {
                    existe = true;
                    break;
                }
            }            
            return existe;
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error al leer el empleado", "Error" , JOptionPane.ERROR_MESSAGE);
            return false;
        }
    
    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jd_Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jd_Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jd_Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jd_Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jd_Nomina dialog = new jd_Nomina(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarE;
    private javax.swing.JButton btnGenerarNomina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtidEmpleado;
    // End of variables declaration//GEN-END:variables
}
