/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Control_Usuario.jd_AgregarUsuario;
import Control_Usuario.jd_ModificarUsuario;
import Control_Usuario.jd_MostrarUsuarios;
import javax.swing.JFrame;

/**
 *
 * @author Yamil
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();        
        this.setLocationRelativeTo(null);
        this.setTitle("Control de Nómina");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); //Maximizar el frm
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Jmi_Salir = new javax.swing.JMenuItem();
        jmi_AgregarEmpleado = new javax.swing.JMenu();
        jmi = new javax.swing.JMenuItem();
        jmi_VerListaEmpleado = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        Jmi_AgregarUsuarios = new javax.swing.JMenuItem();
        Jmi_MostrarUsuarios = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N

        jMenu1.setText("Inicio");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N

        Jmi_Salir.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        Jmi_Salir.setText("Salir");
        Jmi_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jmi_SalirActionPerformed(evt);
            }
        });
        jMenu1.add(Jmi_Salir);

        jMenuBar1.add(jMenu1);

        jmi_AgregarEmpleado.setText("Empleados");
        jmi_AgregarEmpleado.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N

        jmi.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jmi.setText("Agregar Empleado");
        jmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiActionPerformed(evt);
            }
        });
        jmi_AgregarEmpleado.add(jmi);

        jmi_VerListaEmpleado.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jmi_VerListaEmpleado.setText("Ver lista de Empleados");
        jmi_AgregarEmpleado.add(jmi_VerListaEmpleado);

        jMenuBar1.add(jmi_AgregarEmpleado);

        jMenu3.setText("Nomina");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Configuración");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N

        Jmi_AgregarUsuarios.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        Jmi_AgregarUsuarios.setText("Agregar Usuarios");
        Jmi_AgregarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jmi_AgregarUsuariosActionPerformed(evt);
            }
        });
        jMenu4.add(Jmi_AgregarUsuarios);

        Jmi_MostrarUsuarios.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        Jmi_MostrarUsuarios.setText("Mostrar Usuarios");
        Jmi_MostrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jmi_MostrarUsuariosActionPerformed(evt);
            }
        });
        jMenu4.add(Jmi_MostrarUsuarios);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jMenuItem1.setText("Cambiar Contraseña");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jmi_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jmi_SalirActionPerformed
        // TODO add your handling code here:
        Inicio inicio = new Inicio();
        inicio.setVisible(true);    
        this.dispose();    
    }//GEN-LAST:event_Jmi_SalirActionPerformed

    private void Jmi_AgregarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jmi_AgregarUsuariosActionPerformed
        // TODO add your handling code here:
        jd_AgregarUsuario agregarUsuarios = new jd_AgregarUsuario(this, rootPaneCheckingEnabled);
        agregarUsuarios.show();
    }//GEN-LAST:event_Jmi_AgregarUsuariosActionPerformed

    private void Jmi_MostrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jmi_MostrarUsuariosActionPerformed
        // TODO add your handling code here:
        jd_MostrarUsuarios mostrarUsuarios = new jd_MostrarUsuarios(this, rootPaneCheckingEnabled);
        mostrarUsuarios.show();
    }//GEN-LAST:event_Jmi_MostrarUsuariosActionPerformed

    private void jmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jd_ModificarUsuario modificarUsuario = new jd_ModificarUsuario(this, rootPaneCheckingEnabled);
        modificarUsuario.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Jmi_AgregarUsuarios;
    private javax.swing.JMenuItem Jmi_MostrarUsuarios;
    private javax.swing.JMenuItem Jmi_Salir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jmi;
    private javax.swing.JMenu jmi_AgregarEmpleado;
    private javax.swing.JMenuItem jmi_VerListaEmpleado;
    // End of variables declaration//GEN-END:variables
}
